package lt.appcamp.stanleybet.dbms;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import lt.appcamp.stanleybet.dbms.League;
import lt.appcamp.stanleybet.dbms.Region;
import lt.appcamp.stanleybet.dbms.Sport;

import lt.appcamp.stanleybet.dbms.LeagueDao;
import lt.appcamp.stanleybet.dbms.RegionDao;
import lt.appcamp.stanleybet.dbms.SportDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig leagueDaoConfig;
    private final DaoConfig regionDaoConfig;
    private final DaoConfig sportDaoConfig;

    private final LeagueDao leagueDao;
    private final RegionDao regionDao;
    private final SportDao sportDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        leagueDaoConfig = daoConfigMap.get(LeagueDao.class).clone();
        leagueDaoConfig.initIdentityScope(type);

        regionDaoConfig = daoConfigMap.get(RegionDao.class).clone();
        regionDaoConfig.initIdentityScope(type);

        sportDaoConfig = daoConfigMap.get(SportDao.class).clone();
        sportDaoConfig.initIdentityScope(type);

        leagueDao = new LeagueDao(leagueDaoConfig, this);
        regionDao = new RegionDao(regionDaoConfig, this);
        sportDao = new SportDao(sportDaoConfig, this);

        registerDao(League.class, leagueDao);
        registerDao(Region.class, regionDao);
        registerDao(Sport.class, sportDao);
    }
    
    public void clear() {
        leagueDaoConfig.getIdentityScope().clear();
        regionDaoConfig.getIdentityScope().clear();
        sportDaoConfig.getIdentityScope().clear();
    }

    public LeagueDao getLeagueDao() {
        return leagueDao;
    }

    public RegionDao getRegionDao() {
        return regionDao;
    }

    public SportDao getSportDao() {
        return sportDao;
    }

}
