package lt.appcamp.stanleybet.dbms;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table REGION.
 */
public class Region {

    private Long id;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String be_id;
    private Boolean isHot;
    private long regionId;

    public Region() {
    }

    public Region(Long id) {
        this.id = id;
    }

    public Region(Long id, String name, String be_id, Boolean isHot, long regionId) {
        this.id = id;
        this.name = name;
        this.be_id = be_id;
        this.isHot = isHot;
        this.regionId = regionId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getBe_id() {
        return be_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBe_id(String be_id) {
        this.be_id = be_id;
    }

    public Boolean getIsHot() {
        return isHot;
    }

    public void setIsHot(Boolean isHot) {
        this.isHot = isHot;
    }

    public long getRegionId() {
        return regionId;
    }

    public void setRegionId(long regionId) {
        this.regionId = regionId;
    }

}
